---
steps:
- name: 'gcr.io/cloud-builders/docker'
  id: container_build
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/main-elastic-scanner-001:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  id: container_push
  args: ["push", "gcr.io/$PROJECT_ID/main-elastic-scanner-001:$SHORT_SHA"]
  waitFor:
    - container_build
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'elastic-scanner-001', '--image', 'gcr.io/$PROJECT_ID/main-elastic-scanner-001$SHORT_SHA', '--region', 'us-central1', '--platform', 'managed']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-east4-b'
    - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster'
images: ['gcr.io/$PROJECT_ID/main-elastic-scanner-001:$SHORT_SHA']